# Version 3.x introduces additional parameters and is designed to be cross-compatible 
# between Compose and the Docker Engine's swarm mode
version: '3.9'

services:
  frontend: 
    container_name: client
    restart: always
    build: ./client
    ports: 
      - "3000:3000"
    links:
     - backend
  backend:
    container_name: api
    restart: always
    build: ./api
    ports: 
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose: 
      - "27017"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"